#!/usr/bin/python
import os
import console

console.success("Generating Image List ...")

current_path = os.path.dirname(os.path.realpath(__file__))
image_path = os.path.join(current_path, '..', 'dist', 'data')
output_path = os.path.join(current_path, '..', 'dist', 'imageList.js')

image_names = [x for x in os.listdir(image_path) if x.endswith('.png')]


content = [
	'// Autogenerated by %s' %(os.path.basename(__file__)),
	'// Changes to this file will be overwritten',
	'var imageList = [',
]

for name in sorted(image_names):
	content.append('    "%s",' %(name))


content.append('];')

jsFile = open(output_path, "w+")
jsFile.write('\n'.join(content))
jsFile.close()

console.success("Found %d images" %(len(image_names)))
